# Generated by Django 3.2.9 on 2021-11-18 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200, null=True)),
                ('town', models.CharField(max_length=200, null=True)),
                ('county', models.CharField(max_length=200, null=True)),
                ('postcode', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200, null=True)),
                ('town', models.CharField(max_length=200, null=True)),
                ('county', models.CharField(max_length=200, null=True)),
                ('postcode', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=200, null=True)),
                ('customer_email', models.CharField(max_length=200, null=True)),
                ('customer_phone_number', models.CharField(max_length=200, null=True)),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('item_width', models.CharField(max_length=200, null=True)),
                ('item_height', models.CharField(max_length=200, null=True)),
                ('item_length', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AsusLogistic.collectpoint')),
                ('drop_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AsusLogistic.drop')),
                ('receiver_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AsusLogistic.receiver')),
                ('sender_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AsusLogistic.sender')),
            ],
        ),
    ]
