# Generated by Django 3.2.9 on 2021-11-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='collect_ID',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='drop_ID',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='receiver_ID',
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='item_height',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='item_length',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='item_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='item_width',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Receiver',
        ),
    ]
