# Generated by Django 3.2.9 on 2021-12-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='collect_ID',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='drop_ID',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='receiver_ID',
        ),
        migrations.AddField(
            model_name='delivery',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='county',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='item_height',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='item_length',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='item_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='item_width',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='postcode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='sender_ID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AsusLogistic.sender'),
        ),
        migrations.DeleteModel(
            name='Receiver',
        ),
    ]
