# Generated by Django 3.2.9 on 2021-11-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0002_auto_20211118_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='sender_ID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AsusLogistic.sender'),
        ),
    ]
