# Generated by Django 3.2.9 on 2021-11-11 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0002_auto_20211111_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('item_width', models.CharField(max_length=200, null=True)),
                ('item_height', models.CharField(max_length=200, null=True)),
                ('item_length', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sender',
            name='item_ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AsusLogistic.item'),
        ),
    ]
