# Generated by Django 3.2.9 on 2021-11-11 10:41

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0003_auto_20211111_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('item_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AsusLogistic.item')),
                ('sender_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AsusLogistic.sender')),
            ],
        ),
    ]
