# Generated by Django 3.2.9 on 2021-12-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0003_auto_20211215_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectpoint',
            old_name='county2',
            new_name='sender_county',
        ),
        migrations.RenameField(
            model_name='collectpoint',
            old_name='first_name2',
            new_name='sender_last_name',
        ),
        migrations.RenameField(
            model_name='collectpoint',
            old_name='last_name2',
            new_name='sender_name',
        ),
        migrations.RenameField(
            model_name='collectpoint',
            old_name='postcode2',
            new_name='sender_postcode',
        ),
    ]
