# Generated by Django 3.2.9 on 2021-11-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0003_alter_delivery_sender_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='customer',
            new_name='customer_address',
        ),
        migrations.AddField(
            model_name='delivery',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
