# Generated by Django 3.2.9 on 2021-12-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0004_auto_20211215_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectpoint',
            old_name='email',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='collectpoint',
            old_name='sender_county',
            new_name='postcode',
        ),
        migrations.RemoveField(
            model_name='collectpoint',
            name='sender_last_name',
        ),
        migrations.RemoveField(
            model_name='collectpoint',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='collectpoint',
            name='sender_postcode',
        ),
    ]
