# Generated by Django 3.2.9 on 2021-11-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0004_auto_20211111_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200, null=True)),
                ('town', models.CharField(max_length=200, null=True)),
                ('county', models.CharField(max_length=200, null=True)),
                ('postcode', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200, null=True)),
                ('town', models.CharField(max_length=200, null=True)),
                ('county', models.CharField(max_length=200, null=True)),
                ('postcode', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='item_ID',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='sender_ID',
        ),
        migrations.RemoveField(
            model_name='sender',
            name='item_ID',
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AsusLogistic.collectpoint')),
                ('drop_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AsusLogistic.drop')),
                ('receiver_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AsusLogistic.receiver')),
                ('sender_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AsusLogistic.sender')),
            ],
        ),
    ]
