# Generated by Django 3.2.9 on 2021-11-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0005_auto_20211118_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='county',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
