# Generated by Django 3.2.9 on 2021-11-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0005_auto_20211111_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sender',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
