# Generated by Django 3.2.9 on 2021-11-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0006_alter_delivery_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='city',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='county',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='postcode',
        ),
    ]
