# Generated by Django 3.2.9 on 2021-11-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0007_auto_20211118_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='county',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='postcode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
