# Generated by Django 3.2.9 on 2021-11-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0008_auto_20211118_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, null=True)),
                ('password', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
