# Generated by Django 3.2.9 on 2021-12-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0010_person_species'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
