# Generated by Django 3.2.9 on 2021-12-13 17:56

import AsusLogistic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsusLogistic', '0011_auto_20211213_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default=AsusLogistic.models.get_default_profile_image, max_length=255, null=True, upload_to=AsusLogistic.models.get_profile_image_filepath),
        ),
    ]
